[package]
name = "Dynamic Object Replacer"
description = "Framework for loading config files to dynamically replace objects at runtime."
homepage = "https://www.nexusmods.com/morrowind/mods/52105"
repository = "https://github.com/googlepox/MWSE-Dynamic-Object-Replacer"
authors = ["GOOGLEPOX"]
version = "1.2.0"

[tools.mwse]
lua-mod = "GPObjectReplace"
load-order = 100
wait-until-initialized = true

